version: "3"

services:
    HostA:
        image: ubuntu-py-ftp:x64-v1
        container_name: server-10.1.1.11
        hostname:       server
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.1.1.0:
                ipv4_address: 10.1.1.11
                  
    HostM:
        image: ubuntu-py-ftp:x64-v1
        container_name: client-10.1.1.12
        hostname:       client
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.1.1.0:
                ipv4_address: 10.1.1.12

networks:
    net-10.1.1.0:
        name: net-10.1.1.0
        ipam:
            config:
                - subnet: 10.1.1.0/24

